### ISSUE TITLE
Acquisition cannot finalize due to NameError if no recovery was performed

### ISSUE THREAD

**Issue by bwmr** [eisfabian/PACEtomo#10]
Hi, 
Thanks for the great scripts, they really work nicely on our microscope!

In the most recent version of PACEtomo.py, v1.4 - downloaded 30.09.22 I encountered the following bug:

Two groups of targets were set up using PACEtomo_selectTargets.py v1.5. Acquisition was done using "Acquire at Items". The item acquired successfully, however the acquisition could not be finalised with the following error message in the log: 

> Error in Python script  
> Traceback (most recent call last):
> File "<stdin>", line 777, in PACEtomo
> if recoverInput == 1:
> NameError: name 'recoverInput' is not defined

The quickfix was just to comment out lines 777 and 778, but fixing the NameError should also be fairly straightforward. I can test a fix and submit a pull request this week.

Best regards from Zurich,
Benedikt

**Comment by eisfabian** [comment]
Hi Benedikt!

Thanks for letting me know and sorry for the inconvenience! That was an oversight of mine I introduced last minute after I did most of my testing.
I updated the version to 1.4.1 and fixed it.

Thanks again and best,
Fabian

**Comment by bwmr** [comment]
Thanks for the rapid response :)
