### ISSUE TITLE
PACEtomo.py: make target directory selection cancelable

### ISSUE THREAD

**Issue by MoritzWM** [eisfabian/PACEtomo#11]
If the user has the wrong navigator item selected when starting the PACEtomo.py script, they can get stuck in a vicious circle of directory selection and PACEtomo not being able to find target files. I encountered this bug today and the only way out was to create a text file with <note of the navigator entry>.txt, cancelling the script was not possible.

I don't know what sem.UserSetDirectory() or sem.ReportDirectory() return when the user presses cancel, but I think it would be a good idea to add a check.

**Comment by eisfabian** [comment]
Thanks for reporting this! This was indeed a bad one! I fixed it in v1.4.3!
It checks now if the navNote is a text file and it also allows you to click "No" in the message box to exit the loop.

Let me know if you run into any other issues!
Best,
Fabian
