### ISSUE TITLE
Out-of-bounds function code of 615

### ISSUE THREAD

**Issue by MoritzWM** [eisfabian/PACEtomo#13]
Hi,
we recently updated to SerialEM 4.0.20. Since then, selectTargets.py throws the following exception:

`External script interpreter passed an out-of-bounds function code of 615 (maximum is 603)`

The error occurs just after confirming the tracking target. I'm not sure if this is a SerialEM bug or a PACEtomo bug, so I thought I would report it here.
I can also try and narrow down where the bug appears after the Easter holidays.

**Comment by eisfabian** [comment]
Hi Moritz,

On what previous version of SerialEM did it run fine? I do use some functions that are only available in 4.1beta versions. But the error message would probably be different if that was the only problem.
Which version of the selectTargets script are you using?
Did you downgrade SerialEM from 4.1 by any chance?

Best wishes,
Fabian

**Comment by yay110** [comment]
Dear both,

I guess this issue is related to the sem.py Python module that doesn't have the required python function. I would guess the error will pop up when using a new Python script but not after updating serialEM. 

Best wishes
Zhengyi

**Comment by MoritzWM** [comment]
Hi both,
I think it's because we accidentally rolled back SerialEM... so Fabian is right, it was on 4.1 before. We'll go back to 4.1, but I guess we can assume then it will work again.
