### ISSUE TITLE
Feature Suggestion/Request: Optional grid basename

### ISSUE THREAD

**Issue by bbarad** [eisfabian/PACEtomo#17]
I am not sure how common this is, but our naming scheme for TS is currently GRID-ID_LAM#_TS# - this lets us really efficiently combine data from multiple grids for STA and other purposes and keeps bookkeeping simpler. To this end, we've added a variable to the selectTargets script to append a basename (GRID-ID_) to the pacetomo label (which in our case is usually "L1" or similar). This reduces concerns about typos etc from retyping the basename for each set of targets. 

The change is quite small and I'd be happy to share it via pull request, but thought I'd raise here first to see if it would actually be a desired feature for others.

**Comment by eisfabian** [comment]
I see, thanks for the suggestion!
I usually have a completely separate data folder per grid, but it makes sense if you want to combine datasets later.
I'll make it an option in the next version! Soon<sup>TM</sup>

**Comment by bbarad** [comment]
Looks like sampleName addresses this in the 1.6 beta, thanks!!!
