### ISSUE TITLE
Crash in pacetomo.py for new beta 1.6

### ISSUE THREAD

**Issue by bbarad** [eisfabian/PACEtomo#19]
When we run the PaceTomo script with the new beta, we are getting a consistent crash after a few minutes (typically after 5-8 tilts for a lamella with 5 targets).  We can run the same tgts file with the older version of PACEtomo (but with the same settings) and everything works fine, so we are mitigating for now by falling back to that, but I suspect we won't be the only users to run into this. We updated the serialEM beta to beta 15 and are still getting the same crash. If its relevant, we are using python 3.9. The script with our settings is attached, as well as the log leading up to the crash.

[JTL005_4_L09_tgts_run01.txt](https://github.com/eisfabian/PACEtomo/files/11392055/JTL005_4_L09_tgts_run01.txt)
[JTL005_4_L09.log](https://github.com/eisfabian/PACEtomo/files/11392057/JTL005_4_L09.log)
[pacetomobeta.txt](https://github.com/eisfabian/PACEtomo/files/11392059/pacetomobeta.txt)
[JTL005_4_L09_tgts_settings.txt](https://github.com/eisfabian/PACEtomo/files/11392060/JTL005_4_L09_tgts_settings.txt)
[JTL005_4_L09_tgts.txt](https://github.com/eisfabian/PACEtomo/files/11392061/JTL005_4_L09_tgts.txt)

**Comment by bbarad** [comment]
Discovered our python plugin is outdated - this may be the cause of this and #18 - will test ASAP and report back.

**Comment by eisfabian** [comment]
Looks like it happened around the CTFfind call in the script. Does this always happen at the same point of the tilt procedure when it happens? Could you try it with `doCtfFind = False`?

There are no new python commands in that area of the script so I doubt it's caused by the python plugin.

**Comment by eisfabian** [comment]
It looks like David changed something in the CTFfind routine:

3/30/23: Fixed crash in ctffind on images with no Thon rings.

This is from the beta16 release notes.

**Comment by bbarad** [comment]
This is very promising! Thanks for catching it. I'll try again after the upgrade.
