### ISSUE TITLE
Change of LD settings

### ISSUE THREAD

**Issue by wimhagen** [eisfabian/PACEtomo#2]
Hi,

Something to consider for K2 usage: change from View to Search (Krios EFTEM 2250x microprobe) in lines 41 and 161, this way one can keep View at a higher magnification (EFTEM 15K nanoprobe) which helps with eucentric height on older system and with wavy grids, although I have to add that I'm testing lamellae usage on carbon grids...

Best,

Wim Hagen

**Comment by eisfabian** [comment]
Hi Wim!

Thanks for the suggestion. I made it an option in the new version. Let me know in case you stumble across anything else!

Thanks for giving it a try and best,
Fabian

**Comment by wimhagen** [comment]
Hi Fabian,

Thanks for the fast response, the 1.3 version for setting up targets works for the typical recipe used here (montaged maps at 8700x on K2).

Best,

Wim
