### ISSUE TITLE
"Error writing data in the background to file"

### ISSUE THREAD

**Issue by congarr** [eisfabian/PACEtomo#23]
We are attempting to run PACEtomo following the guide for holey support and are unable to complete collecting a til series. Using a 3X3 grid, we get through the 0 degree images and just begin the 3 degree tilts when we get the error:

"Error writing data in the background to file:
Error opening new TIFF file.

The unsaved image is now in buffer Q
After fixing the problem if possible, save the image with the "Save Active" button or "Save Active" or "Save to Other/Save Single" commands in the file menu"

- We're using PACEtomo.py v1.4.4. 
- We've tried both our usual network storage and saving locally. 
- It doesn't seem to be a permission issue.
- We tried turning off save frames, no change.
- Probably got this error six or seven times trying different things each time.

Could very well be a SerialEM error or something with our systems, but we've never seen it before. Represenative log below. Excuse the filenames, you know how troubleshooting goes. 

[poop2.log](https://github.com/eisfabian/PACEtomo/files/13048660/poop2.log)

**Comment by eisfabian** [comment]
Hey!

Thanks for reaching out!
I've never seen this before either. There should be no TIFF files involved. Could you send me your "*_tgts.txt" file? Does it specify any TIF file names?

It looks like SerialEM tries to add the next tilt image to the file, which is only possible for MRC files, but for some reason it seemed to have saved it as a TIF file.

Best,
Fabian

**Comment by congarr** [comment]
Hi Fabian,

Thanks for the reply! I'm working on getting the corresponding _tgts.txt file for the error. 

In the meantime, my center collects everything as .tifs, so that might just be it! I'll keep you updated on of this is an us problem or a pacetomo problem! 

Thanks much!
Connor

**Comment by congarr** [comment]
Hi Fabian,

Here is a new .log (more appropriately named) and its corresponding _tgts.txt file. Thanks a bunch! 

[test12_tgts.txt](https://github.com/eisfabian/PACEtomo/files/13182513/test12_tgts.txt)
[test12.log](https://github.com/eisfabian/PACEtomo/files/13182515/test12.log)

**Comment by eisfabian** [comment]
Thank you, Connor!

This time it went well beyond the second tilt step, which means it's not a problem with the TS stack.
The frame saving itself seems to start failing, which would make it a SerialEM issue, maybe a storage issue? Although you did try it on 2 different destinations by the look of it.

Do you experience it using the normal SerialEM tilt series controller? Or during a SPA acquisition?

Sorry, I couldn't be of more help!

Best wishes,
Fabian
