### ISSUE TITLE
Initial zoom during target selection

### ISSUE THREAD

**Issue by asarnow** [eisfabian/PACEtomo#24]
Hi Fabian,
SerialEM's habit of setting an odd initial zoom after taking a picture is hitting me constantly during target selection. The preview image is zoomed in very far so I can't see if it's targeted well without exposing a second time (guidance = True) or I don't have enough time to change the zoom before using hotkeys (guidance = False). Is there a way to force a reasonable initial zoom either in selectTargets or through SerialEM itself? Thanks!

**Comment by eisfabian** [comment]
Hey!

Yeah, the zoom can indeed get quite annoying. The feeling I got is that it helps to have the same binning for View and Record and the other problem is that you are probably zoomed in a lot to see your feature in View mode. It probably keeps the same zoom level when you switch to Record. So it should help to zoom out before you go for the Preview image.
Those are just some ideas off the top of my head.

Having a reset zoom command would be great for this particular use case, I guess. Or generally having SerialEM reset the zoom when the mag is changed.

I'll put it on my list of SerialEM suggestions!

Thanks and good luck!
Fabian
