### ISSUE TITLE
Suggestion: Binned and ordered TS

### ISSUE THREAD

**Issue by shahpnmlab** [eisfabian/PACEtomo#27]
Hi Fabian,
Would you consider adding an option to the PACETomo script, by which a user can define generating smaller ordered TS stacks? I can see that you already have a reordering function, so perhaps binning may also be added? This way, the user can potentially save space on the scope computer. Additionally, could a user also have an option to simply turn off storing the TS?
Best,
Pranav

**Comment by eisfabian** [comment]
Hi Pranav,

Thanks for the suggestion!
I do need to store the TS for realignment during acquisition. But I could include an option to delete it after acquisition is done. 
Quick and dirty binning should not be an issue. The question is: do you also want an mdoc file written accordingly?

Which of these options would be your preference?

Thanks and best,
Fabian

**Comment by shahpnmlab** [comment]
Removing after collection sounds good! 
Re binning - In my view there are broadly three use cases 
(a) High res STA of macromolecules 
(b) Morphological studies of the object 
(c). Quick look see for determing "good data"
In case (a) most users rarely use the assembled tilt-stacks and prefer to perform pre-processing in all the different software packages, for these use cases, there is no benefit in keeping full-res stacks. But unmodified mdocs for the stacks is super critical.
In cases (b) and (c) a coarsely binned stack is OK since the level information being seeked is not affected by the high res information (indeed binning may help with contrast). 

In both cases i dont think the mdoc file needs to be perturbed and should reflect the data collection params (because loss of this information is irretrievable).

**Comment by eisfabian** [comment]
Ok! This is implemented and should come in v1.8.1 soon with a few other small tweaks. I just want to get a bit more testing done before releasing it.
Let me know if you want to already give it a try!

Best,
Fabian

**Comment by eisfabian** [comment]
Now available in v1.8.1. Let me know if you run into any issues!
Thanks again for the suggestion!

Best,
Fabian

**Comment by shahpnmlab** [comment]
Thanks Fabian!

**Comment by shahpnmlab** [comment]
Hi Fabian,
Separately we see a systematic shit in the data collected with a pre-tilt.
See below more details from our senior staff scientist. Could you suggest
any fixes or provide advice?
========
We are exclusively using the pacetomo from montage to position our target
(this works really nicely). However, when we were using Pacetomo to collect
TS on a lamella with a pre-tilt (generally 12 degrees), we observe a
systematic shift of the 1st and 4th images relative to the rest of the tilt
series. This corresponds to the 1st image collected on the positive tilts
side and the 1st image on the negative tilts side. This doesn’t happen when
we collect on samples without pre-tilt and we would like to try improving
things. We are always using the preview align option and in addition we
tried to use the view align option but this doesn’t fix this behaviour.
What we think might be helpful are the following option: (A) Have the
preview align happening at 0 degree tilt to re-centre only the tracking TS,
then go to the pre-tilt to redo preview align on the tracking TS first and
then preview align on all the targets. (B) After the preview align, go to
the pre-tilt. Collect the first image but instead of re-aligning relative
to the template from the montage, skip the re-alignment and use that image
as a reference for the next tilts, including the first one on the negative
side. The drawback is that the tilt series will be offsetted compared to
the target but the gain is that you don't have to exclude the initial tilts
which are the best.
========
Best,
Pranav
--
Pranav Shah
Postdoctoral Research Fellow.

Division of Structural Biology,
Wellcome Trust Centre for Human Genetics,
University of Oxford,
Roosevelt Drive, Oxford OX3 7BN,
UK

**Comment by eisfabian** [comment]
Hi Pranav,

Okay, to clarify:
- Does this happen when doing the normal target selection on a lamella with pretilt? Or is this unique to the targetsFromMontage setup?
- Do you measure the pretilt or do you enter it according to your FIB milling incidence angle? Have you tried using the opposite pretilt sign?
-  During the previewAli routine, does it look like it is aligning the image properly to the reference?

Thanks and best,
Fabian

**Comment by shahpnmlab** [comment]
Hi Fabian, 
Below is his response -
1.⁠ ⁠No, it doesn't happen with the normal target selection but will have to re-test with the latest version.
2.⁠ ⁠We only use the one from the FIB and we think our pre-tilt values are having correct sign.
3.⁠ ⁠Yes, it seems to be able to align the target properly.

**Comment by eisfabian** [comment]
Thanks, Pranav!

I was reading description of the problem again and do I understand correctly that (A) and (B) are requests for features and not something you already tried?

If so, (B) should be achievable by simply disabling both previewAli and viewAli. Then PACEtomo will only align to the tracking tilt series and only use the relative image shifts from there without aligning to the template.

Another question: Do you collect the montage for target cropping at 0º stage tilt? Or do you try to compensate for the pretilt? Also what is the startTilt you use? PACEtomo assumes target selection at 0º, but if the preview alignment to the template step looked sensible that should not be the issue.

Could you send me a log file of a run where the 1st and 4th image showed a large error?

I haven't tested the targetsFromMontage script on lamellae for a long time. But SPACEtomo is using pretty much the same approach (viewAli only) and I didn't notice such issues. I will try to test the targetsFromMontage script in my next session in a few weeks.

**Comment by shahpnmlab** [comment]
Hi Fabian, Can you write to me at p[dot]shah[dot]lab[at]gmail[dot]com? I am unable to reach you at your tokyo email id.
