### ISSUE TITLE
Exposure area label not centered on the record image

### ISSUE THREAD

**Issue by shahpnmlab** [eisfabian/PACEtomo#4]
Hi Fabian,
Thanks for including a label that indicates the area that will be exposed in a resulting tilt series. HOwever I noticed that the ellipsoid is not centerd on the record image. Could you suggest why this might be the case?
![Untitled](https://user-images.githubusercontent.com/34034134/180418841-8306cbdb-33e4-46c8-bd96-77d6e4561d3a.jpg)
could it be that the initial estimations of the tilt rotation and lamela pre-tilt are off and that is what leads to an accumulation of errors?

**Comment by eisfabian** [comment]
Hey!

Thanks! Did you use v1.4.1? There is an option to set the tilt axis offset. If you didn't set it again in the script, it is probably off by that offset. At the time I could not read the tilt axis offset from SerialEM.
There will be a new target selection script soon that makes it a lot easier to draw these exposure areas, but it will require to upgrade to the new SerialEM version.

Let me know if there are further issues!
Best,
Fabian
