### ISSUE TITLE
Feature Request: Different settings for tracking position

### ISSUE THREAD

**Issue by bbarad** [eisfabian/PACEtomo#5]
I'd like to start collecting lower defocus images, but am worried about tracking not working as well. Would it be possible to set a different defocus or exposure time for the tracking position relative to the remainder of the images? I'm imagining tracking with defocus 8um and collecting with 1-4 micron defocus.

**Comment by eisfabian** [comment]
Thanks for the suggestions! Yeah, that should be no problem. I just implemented a custom exposure time for the first tilt image. I could probably do something similar for the first position and include a simple fixed defocus offset. I'll put it on my list!

PS: I just saw that the longer exposure time for the tracking series was already on my list! :D

**Comment by eisfabian** [comment]
This is now possible with v1.4!
