### ISSUE TITLE
Feature request: Cancel addition of new point after group

### ISSUE THREAD

**Issue by bbarad** [eisfabian/PACEtomo#6]
I am using the group of points workflow on lamellae and it is working great! I occasionally want to continue after the group of points to see if its worth adding something just outside of my high mag polygon montage. Often I end up adding a point, but sometimes I decide its not worth it - but there is no way to not add a position once I get into that workflow. It would be great to have the final yes/no decision about whether a given point gets added lead to another user prompt about whether to continue - right now it just goes back to the view mag to pick another position. 

Pretty sure I see how to fix this - happy to submit a PR if you are up for taking one and would rather not do it!

**Comment by eisfabian** [comment]
Yeah, I also ran into that from time to time. I just stopped the script at that point. The target file gets updated at every addition, so there is nothing necessary happening at the end of the script.
It would be cleaner to have another pop-up though, you are right.

I will probably release a larger update to the target script at some point and will include it then!

**Comment by eisfabian** [comment]
This is fixed in selectTargets v.1.5!
