### ISSUE TITLE
Feature Request: Imbalanced Tilts

### ISSUE THREAD

**Issue by bbarad** [eisfabian/PACEtomo#7]
I mill with an 11º angle, so mill with a starting angle of -11º. Because of that, the tilt range I can use are limited to around 48 (our tilt controller is a little dodgy past ±60º, I prefer not to use it). I'd like to be able to go past +37º, though - that extra tilt range won't give much structure information but helps a lot with segmentations. Would it be possible to define a larger tilt range and just have "extra" tilts get removed/not used instead of throwing an error? 

Happy to work on this an submit a PR.

**Comment by eisfabian** [comment]
I was asked this before, so I am willing to implement it. It should be easy since I have a skip flag for every branch of every position. I just have to add a check if all positions are set to "skip" and in that case avoid tilting to that angle altogether. I'll put it on the list!

**Comment by bbarad** [comment]
Thanks very much! Sorry to add so many things to your list but sounds like they are all not too painful!

**Comment by eisfabian** [comment]
This is now possible in v1.4!
