### ISSUE TITLE
restart/continue tilt series after changing image shift limit

### ISSUE THREAD

**Issue by cbiertue** [eisfabian/PACEtomo#8]
Hi,
I got an error that I reached the image shift limit in the middle of my tilt collection. I modified the PACEtomo script to increase the limit. How can I continue or restart my tilt series after the last collected position before the error?

Thanks, christian

**Comment by eisfabian** [comment]
Hi Christian,

sorry for the late reply. Which PACEtomo version were you using? Version 1.2 or higher should be able to detect when a TS gets close to the image shift limit and abort only that one TS. So it should keep collecting all the others.

In any case, right now continuation of a PACEtomo run is not possible. I am currently working on this and hope that stopping and continuing a run will be possible at least if the stage was not moved.

Thanks and best,
Fabian

**Comment by eisfabian** [comment]
Resuming a run is now possible in v1.4!
